### ISSUE TITLE
ghc-make can't find package?

### ISSUE THREAD

**Issue by KeesBleijenberg** [ndmitchell/ghc-make#9]
Compiling with ghc --make is slow. So I installed ghc-make  on a windows 64 bits machine with ghc version 7.8.3 on it.  Then I did
ghc-make -j4 -threaded -O2 -rtsopts Xls2Prog 

and got:

# ghc-pkg (for .ghc-make.pkgs)
Error when running Shake build system:
* .ghc-make.result
* Hulpfunc.o
* Hulpfunc.o Hulpfunc.hi
* (x86)/Haskell Platform/2014.2.0.0/lib/containers-0.5.5.1/Data/Map.hi
Error, file does not exist and no rule available:
  (x86)/Haskell Platform/2014.2.0.0/lib/containers-0.5.5.1/Data/Map.hi

With ghc --make there is no error message,

Kees

**Comment by ndmitchell** [comment]
This bug is a bug in the Makefile parser which is fixed in the HEAD version of Shake. I deal with at most one space in a Makefile atom, but if your directory has 2 (or 3 in your case) it breaks the line incorrectly.

I'm hoping to release a new version of Shake shortly (next few days) but am held up by a miscompilation introduced in GHC 7.10.1 RC3 which I need to track down first. In the meantime either wait a little, or install HEAD shake and recompile ghc-make.

**Comment by ndmitchell** [comment]
OK, Shake has been released now. Do `cabal update && cabal install shake && cabal install ghc-make` and hopefully it will just work.

**Comment by KeesBleijenberg** [comment]
No errors anymore.

Thanks !

Kees

 

Van: Neil Mitchell [mailto:notifications@github.com] 
Verzonden: donderdag 26 maart 2015 15:54
Aan: ndmitchell/ghc-make
CC: KeesBleijenberg
Onderwerp: Re: [ghc-make] ghc-make can't find package? (#9)

 

Closed #9 <https://github.com/ndmitchell/ghc-make/issues/9> .
